# Thesis-level metadata
title: "Object Storage Lake Tables TCO Displacement"
thesis: "object-storage-lake-tables-tco"
artifact: "thesis-root"
version: "1.0"
status: "active"
authors: ["Patrick McFadin"]
created: "2025-08-17"
updated: "2025-08-17"
license: "CC-BY-4.0"
keywords: ["object-storage", "lake-tables", "tco", "decoupled-compute", "analytics", "cloud-first", "table-formats", "db-native-storage"]